name: main
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        node:
          - version: 20.x
          - version: 22.x
          - version: 24.x
    runs-on: ubuntu-22.04
    name: Tests on Node.js v${{ matrix.node.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node.version }}

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Build sources
        run: ${{ matrix.node.env }} npm run build

      - name: Run tests
        run: ${{ matrix.node.env }} npm run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Run lint
        run: npm run lint
